<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('municipios')->truncate();

        $municipios = [
            [
                'pais_id' => '186',
                'provincia_id' => '1',
                'descripcion' => 'SANTO DOMINGO DE GUZMÁN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'AZUA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'LAS CHARCAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'LAS YAYAS DE VIAJAMA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'PADRE DE LAS CASAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'PERALTA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'SABANA YEGUA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'PUEBLO VIEJO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'TÁBARA ARRIBA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'GUAYABAL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '2',
                'descripcion' => 'ESTEBANÍA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '3',
                'descripcion' => 'NEIBA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '3',
                'descripcion' => 'GALVÁN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '3',
                'descripcion' => 'TAMAYO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '3',
                'descripcion' => 'VILLA JARAGUA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '3',
                'descripcion' => 'LOS RÍOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'BARAHONA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'CABRAL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'ENRIQUILLO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'PARAÍSO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'VICENTE NOBLE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'EL PEÑÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'LA CIÉNAGA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'FUNDACIÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'LAS SALINAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'POLO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '4',
                'descripcion' => 'JAQUIMEYES',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '5',
                'descripcion' => 'DAJABÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '5',
                'descripcion' => 'LOMA DE CABRERA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '5',
                'descripcion' => 'PARTIDO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '5',
                'descripcion' => 'RESTAURACIÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '5',
                'descripcion' => 'EL PINO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'SAN FRANCISCO DE MACORÍS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'ARENOSO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'CASTILLO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'PIMENTEL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'VILLA RIVA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'LAS GUÁRANAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '6',
                'descripcion' => 'EUGENIO MARÍA DE HOSTOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'COMENDADOR',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'BÁNICA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'EL LLANO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'HONDO VALLE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'PEDRO SANTANA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '7',
                'descripcion' => 'JUAN SANTIAGO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '8',
                'descripcion' => 'EL SEIBO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '8',
                'descripcion' => 'MICHES',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '9',
                'descripcion' => 'MOCA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '9',
                'descripcion' => 'CAYETANO GERMOSÉN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '9',
                'descripcion' => 'GASPAR HERNÁNDEZ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '9',
                'descripcion' => 'JAMAO AL NORTE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'JIMANÍ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'DUVERGÉ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'LA DESCUBIERTA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'POSTRER RÍO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'CRISTÓBAL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '10',
                'descripcion' => 'MELLA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '11',
                'descripcion' => 'HIGÜEY',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '11',
                'descripcion' => 'SAN RAFAEL DEL YUMA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '12',
                'descripcion' => 'LA ROMANA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '12',
                'descripcion' => 'GUAYMATE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '12',
                'descripcion' => 'VILLA HERMOSA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '13',
                'descripcion' => 'LA VEGA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '13',
                'descripcion' => 'CONSTANZA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '13',
                'descripcion' => 'JARABACOA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '13',
                'descripcion' => 'JIMA ABAJO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '14',
                'descripcion' => 'NAGUA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '14',
                'descripcion' => 'CABRERA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '14',
                'descripcion' => 'EL FACTOR',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '14',
                'descripcion' => 'RÍO SAN JUAN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'MONTE CRISTI',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'CASTAÑUELAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'GUAYUBÍN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'LAS MATAS DE SANTA CRUZ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'PEPILLO SALCEDO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '15',
                'descripcion' => 'VILLA VÁSQUEZ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '16',
                'descripcion' => 'PEDERNALES',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '16',
                'descripcion' => 'OVIEDO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '17',
                'descripcion' => 'BANÍ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '17',
                'descripcion' => 'NIZAO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'PUERTO PLATA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'ALTAMIRA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'GUANANICO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'IMBERT',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'LOS HIDALGOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'LUPERÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'SOSÚA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'VILLA ISABELA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '18',
                'descripcion' => 'VILLA MONTELLANO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '19',
                'descripcion' => 'SALCEDO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '19',
                'descripcion' => 'TENARES',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '19',
                'descripcion' => 'VILLA TAPIA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '20',
                'descripcion' => 'SAMANÁ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '20',
                'descripcion' => 'SÁNCHEZ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '20',
                'descripcion' => 'LAS TERRENAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'SAN CRISTÓBAL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'SABANA GRANDE DE PALENQUE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'BAJOS DE HAINA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'CAMBITA GARABITOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'VILLA ALTAGRACIA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'YAGUATE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'SAN GREGORIO DE NIGUA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '21',
                'descripcion' => 'LOS CACAOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'SAN JUAN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'BOHECHÍO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'EL CERCADO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'JUAN DE HERRERA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'LAS MATAS DE FARFÁN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '22',
                'descripcion' => 'VALLEJUELO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'SAN PEDRO DE MACORÍS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'LOS LLANOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'RAMÓN SANTANA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'CONSUELO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'QUISQUEYA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '23',
                'descripcion' => 'GUAYACANES',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '24',
                'descripcion' => 'COTUÍ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '24',
                'descripcion' => 'CEVICOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '24',
                'descripcion' => 'FANTINO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '24',
                'descripcion' => 'LA MATA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'SANTIAGO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'BISONÓ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'JÁNICO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'LICEY AL MEDIO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'SAN JOSÉ DE LAS MATAS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'TAMBORIL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'VILLA GONZÁLEZ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'PUÑAL',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '25',
                'descripcion' => 'SABANA IGLESIA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '26',
                'descripcion' => 'SAN IGNACIO DE SABANETA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '26',
                'descripcion' => 'VILLA LOS ALMÁCIGOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '26',
                'descripcion' => 'MONCIÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '27',
                'descripcion' => 'MAO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '27',
                'descripcion' => 'ESPERANZA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '27',
                'descripcion' => 'LAGUNA SALADA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '28',
                'descripcion' => 'BONAO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '28',
                'descripcion' => 'MAIMÓN',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '28',
                'descripcion' => 'PIEDRA BLANCA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '29',
                'descripcion' => 'MONTE PLATA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '29',
                'descripcion' => 'BAYAGUANA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '29',
                'descripcion' => 'SABANA GRANDE DE BOYÁ',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '29',
                'descripcion' => 'YAMASA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '29',
                'descripcion' => 'PERALVILLO',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '30',
                'descripcion' => 'HATO MAYOR',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '30',
                'descripcion' => 'SABANA DE LA MAR',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '30',
                'descripcion' => 'EL VALLE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '31',
                'descripcion' => 'SAN JOSÉ DE OCOA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '31',
                'descripcion' => 'SABANA LARGA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '31',
                'descripcion' => 'RANCHO ARRIBA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'SANTO DOMINGO ESTE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'SANTO DOMINGO OESTE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'SANTO DOMINGO NORTE',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'BOCA CHICA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'SAN ANTONIO DE GUERRA',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'LOS ALCARRIZOS',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'pais_id' => '186',
                'provincia_id' => '32',
                'descripcion' => 'PEDRO BRAND',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
        ];

        DB::table('municipios')->insert($municipios);
    }
}
