<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('paises')->truncate();

        $paises = [
            [
                'codigo' => 'AFG',
                'iso' => 'AF',
                'descripcion' => 'Afganistán',
                'nacionalidad' => 'Afgana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ALB',
                'iso' => 'AL',
                'descripcion' => 'Albania',
                'nacionalidad' => 'Albana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DEU',
                'iso' => 'DE',
                'descripcion' => 'Alemania',
                'nacionalidad' => 'Alemana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AND',
                'iso' => 'AD',
                'descripcion' => 'Andorra',
                'nacionalidad' => 'Andorrana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AGO',
                'iso' => 'AO',
                'descripcion' => 'Angola',
                'nacionalidad' => 'Angolana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AIA',
                'iso' => 'AI',
                'descripcion' => 'Anguila',
                'nacionalidad' => 'Anguilana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ATA',
                'iso' => 'AQ',
                'descripcion' => 'Antártida',
                'nacionalidad' => 'Antártica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ATG',
                'iso' => 'AG',
                'descripcion' => 'Antigua y Barbuda',
                'nacionalidad' => 'Antiguana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ANH',
                'iso' => 'AN',
                'descripcion' => 'Antillas Holandesas',
                'nacionalidad' => 'Holandesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SAU',
                'iso' => 'SA',
                'descripcion' => 'Arabia Saudita',
                'nacionalidad' => 'Saudí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DZA',
                'iso' => 'DZ',
                'descripcion' => 'Argelia',
                'nacionalidad' => 'Argelina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ARG',
                'iso' => 'AR',
                'descripcion' => 'Argentina',
                'nacionalidad' => 'Argentina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ARM',
                'iso' => 'AM',
                'descripcion' => 'Armenia',
                'nacionalidad' => 'Armenia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ABW',
                'iso' => 'AW',
                'descripcion' => 'Aruba',
                'nacionalidad' => 'Arubiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AUS',
                'iso' => 'AU',
                'descripcion' => 'Australia',
                'nacionalidad' => 'Australiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AUT',
                'iso' => 'AT',
                'descripcion' => 'Austria',
                'nacionalidad' => 'Austriaca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AZE',
                'iso' => 'AZ',
                'descripcion' => 'Azerbaiyán',
                'nacionalidad' => 'Azerbaiyana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BHS',
                'iso' => 'BS',
                'descripcion' => 'Bahamas',
                'nacionalidad' => 'Bahameña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BHR',
                'iso' => 'BH',
                'descripcion' => 'Baréin',
                'nacionalidad' => 'Bareiní',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BGD',
                'iso' => 'BD',
                'descripcion' => 'Bangladés',
                'nacionalidad' => 'Bangladesí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BRB',
                'iso' => 'BB',
                'descripcion' => 'Barbados',
                'nacionalidad' => 'Barbadense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BLR',
                'iso' => 'BY',
                'descripcion' => 'Belarús',
                'nacionalidad' => 'Bielorusa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BEL',
                'iso' => 'BE',
                'descripcion' => 'Bélgica',
                'nacionalidad' => 'Belga',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BLZ',
                'iso' => 'BZ',
                'descripcion' => 'Belice',
                'nacionalidad' => 'Beliceña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BEN',
                'iso' => 'BJ',
                'descripcion' => 'Benín',
                'nacionalidad' => 'Beninés',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BMU',
                'iso' => 'BM',
                'descripcion' => 'Bermudas',
                'nacionalidad' => 'Bermudeña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BTN',
                'iso' => 'BT',
                'descripcion' => 'Bhután',
                'nacionalidad' => 'Butanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BOL',
                'iso' => 'BO',
                'descripcion' => 'Bolivia',
                'nacionalidad' => 'Boliviana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BIH',
                'iso' => 'BA',
                'descripcion' => 'Bosnia y Herzegovina',
                'nacionalidad' => 'Bosnia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BWA',
                'iso' => 'BW',
                'descripcion' => 'Botsuana',
                'nacionalidad' => 'Botsuana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BRA',
                'iso' => 'BR',
                'descripcion' => 'Brasil',
                'nacionalidad' => 'Brasileña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BRN',
                'iso' => 'BN',
                'descripcion' => 'Brunéi',
                'nacionalidad' => 'Bruneana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BGR',
                'iso' => 'BG',
                'descripcion' => 'Bulgaria',
                'nacionalidad' => 'Búlgara',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BFA',
                'iso' => 'BF',
                'descripcion' => 'Burkina Faso',
                'nacionalidad' => 'Burkinesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BDI',
                'iso' => 'BI',
                'descripcion' => 'Burundi',
                'nacionalidad' => 'Burundesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CPV',
                'iso' => 'CV',
                'descripcion' => 'Cabo Verde',
                'nacionalidad' => 'Caboverdiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KHM',
                'iso' => 'KH',
                'descripcion' => 'Camboya',
                'nacionalidad' => 'Camboyesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CMR',
                'iso' => 'CM',
                'descripcion' => 'Camerún',
                'nacionalidad' => 'Camerunésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CAN',
                'iso' => 'CA',
                'descripcion' => 'Canadá',
                'nacionalidad' => 'Canadiense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TCD',
                'iso' => 'TD',
                'descripcion' => 'Chad',
                'nacionalidad' => 'Chadiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CHL',
                'iso' => 'CL',
                'descripcion' => 'Chile',
                'nacionalidad' => 'Chilena',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CHN',
                'iso' => 'CN',
                'descripcion' => 'China',
                'nacionalidad' => 'China',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CYP',
                'iso' => 'CY',
                'descripcion' => 'Chipre',
                'nacionalidad' => 'Chipriota',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VAT',
                'iso' => 'VA',
                'descripcion' => 'Ciudad del Vaticano',
                'nacionalidad' => 'Vaticana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'COL',
                'iso' => 'CO',
                'descripcion' => 'Colombia',
                'nacionalidad' => 'Colombiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'COM',
                'iso' => 'KM',
                'descripcion' => 'Comoras',
                'nacionalidad' => 'Comorense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'COG',
                'iso' => 'CG',
                'descripcion' => 'Congo',
                'nacionalidad' => 'Congoleña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PRK',
                'iso' => 'KP',
                'descripcion' => 'Corea del Norte',
                'nacionalidad' => 'Norcoreana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KOR',
                'iso' => 'KR',
                'descripcion' => 'Corea del Sur',
                'nacionalidad' => 'Surcoreana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CIV',
                'iso' => 'CI',
                'descripcion' => 'Costa de Marfil',
                'nacionalidad' => 'Marfileña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CRI',
                'iso' => 'CR',
                'descripcion' => 'Costa Rica',
                'nacionalidad' => 'Costarricense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HRV',
                'iso' => 'HR',
                'descripcion' => 'Croacia',
                'nacionalidad' => 'Croata',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CUB',
                'iso' => 'CU',
                'descripcion' => 'Cuba',
                'nacionalidad' => 'Cubana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DNK',
                'iso' => 'DK',
                'descripcion' => 'Dinamarca',
                'nacionalidad' => 'Danés',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DMA',
                'iso' => 'DM',
                'descripcion' => 'Dominica',
                'nacionalidad' => 'Dominiqués',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ECU',
                'iso' => 'EC',
                'descripcion' => 'Ecuador',
                'nacionalidad' => 'Ecuatoriana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'EGY',
                'iso' => 'EG',
                'descripcion' => 'Egipto',
                'nacionalidad' => 'Egipcia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SLV',
                'iso' => 'SV',
                'descripcion' => 'El Salvador',
                'nacionalidad' => 'Salvadoreña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ARE',
                'iso' => 'AE',
                'descripcion' => 'Emiratos Árabes Unidos',
                'nacionalidad' => 'Arabe',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ERI',
                'iso' => 'ER',
                'descripcion' => 'Eritrea',
                'nacionalidad' => 'Eritrea',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SVK',
                'iso' => 'SK',
                'descripcion' => 'Eslovaquia',
                'nacionalidad' => 'Eslovaca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SVN',
                'iso' => 'SI',
                'descripcion' => 'Eslovenia',
                'nacionalidad' => 'Eslovaca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ESP',
                'iso' => 'ES',
                'descripcion' => 'España',
                'nacionalidad' => 'Española',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'USA',
                'iso' => 'US',
                'descripcion' => 'Estados Unidos de América',
                'nacionalidad' => 'Estadounidense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'EST',
                'iso' => 'EE',
                'descripcion' => 'Estonia',
                'nacionalidad' => 'Estonia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ETH',
                'iso' => 'ET',
                'descripcion' => 'Etiopía',
                'nacionalidad' => 'Etíope',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FJI',
                'iso' => 'FJ',
                'descripcion' => 'Fiji',
                'nacionalidad' => 'Fiyiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PHL',
                'iso' => 'PH',
                'descripcion' => 'Filipinas',
                'nacionalidad' => 'Filipina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FIN',
                'iso' => 'FI',
                'descripcion' => 'Finlandia',
                'nacionalidad' => 'Finlandés',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FRA',
                'iso' => 'FR',
                'descripcion' => 'Francia',
                'nacionalidad' => 'Francesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GAB',
                'iso' => 'GA',
                'descripcion' => 'Gabón',
                'nacionalidad' => 'Gabonésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GMB',
                'iso' => 'GM',
                'descripcion' => 'Gambia',
                'nacionalidad' => 'Gambiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GEO',
                'iso' => 'GE',
                'descripcion' => 'Georgia',
                'nacionalidad' => 'Georgiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GSI',
                'iso' => 'GS',
                'descripcion' => 'Georgia del Sur e Islas Sandwich del Sur',
                'nacionalidad' => 'Georgiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GHA',
                'iso' => 'GH',
                'descripcion' => 'Ghana',
                'nacionalidad' => 'Ghanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GIB',
                'iso' => 'GI',
                'descripcion' => 'Gibraltar',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GRD',
                'iso' => 'GD',
                'descripcion' => 'Granada',
                'nacionalidad' => 'Granadina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GRC',
                'iso' => 'GR',
                'descripcion' => 'Grecia',
                'nacionalidad' => 'Greca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GRL',
                'iso' => 'GL',
                'descripcion' => 'Groenlandia',
                'nacionalidad' => 'Groenlandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GLP',
                'iso' => 'GP',
                'descripcion' => 'Guadalupe',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GUM',
                'iso' => 'GU',
                'descripcion' => 'Guam',
                'nacionalidad' => 'Agañésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GTM',
                'iso' => 'GT',
                'descripcion' => 'Guatemala',
                'nacionalidad' => 'Guatemalteca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GYN',
                'iso' => 'GY',
                'descripcion' => 'Guyana',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GUF',
                'iso' => 'GF',
                'descripcion' => 'Guayana Francesa',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GGY',
                'iso' => 'GG',
                'descripcion' => 'Guernsey',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GIN',
                'iso' => 'GN',
                'descripcion' => 'Guinea',
                'nacionalidad' => 'Guineana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GNQ',
                'iso' => 'GQ',
                'descripcion' => 'Guinea Ecuatorial',
                'nacionalidad' => 'Ecuatoguineana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GNB',
                'iso' => 'GW',
                'descripcion' => 'Guinea-Bissau',
                'nacionalidad' => 'Guineana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HTI',
                'iso' => 'HT',
                'descripcion' => 'Haití',
                'nacionalidad' => 'Haitiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HND',
                'iso' => 'HN',
                'descripcion' => 'Honduras',
                'nacionalidad' => 'Hondureña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HKG',
                'iso' => 'HK',
                'descripcion' => 'Hong Kong',
                'nacionalidad' => 'Japonésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HUN',
                'iso' => 'HU',
                'descripcion' => 'Hungría',
                'nacionalidad' => 'Húngara',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IND',
                'iso' => 'IN',
                'descripcion' => 'India',
                'nacionalidad' => 'India',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IDN',
                'iso' => 'ID',
                'descripcion' => 'Indonesia',
                'nacionalidad' => 'Indonésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IRQ',
                'iso' => 'IQ',
                'descripcion' => 'Iraq',
                'nacionalidad' => 'Iraquí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IRN',
                'iso' => 'IR',
                'descripcion' => 'Irán',
                'nacionalidad' => 'Iraní',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IRL',
                'iso' => 'IE',
                'descripcion' => 'Irlanda',
                'nacionalidad' => 'Irlandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BVT',
                'iso' => 'BV',
                'descripcion' => 'Isla Bouvet',
                'nacionalidad' => 'Noruega',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IDM',
                'iso' => 'IM',
                'descripcion' => 'Isla de Man',
                'nacionalidad' => 'Manlandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ISL',
                'iso' => 'IS',
                'descripcion' => 'Islandia',
                'nacionalidad' => 'Islandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'AXD',
                'iso' => 'AX',
                'descripcion' => 'Islas Áland',
                'nacionalidad' => 'Alandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CYM',
                'iso' => 'KY',
                'descripcion' => 'Islas Caimán',
                'nacionalidad' => 'Caimanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CXR',
                'iso' => 'CX',
                'descripcion' => 'Islas de Navidad',
                'nacionalidad' => 'Navidense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CCK',
                'iso' => 'CC',
                'descripcion' => 'Islas Cocos',
                'nacionalidad' => 'Malayésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'COK',
                'iso' => 'CK',
                'descripcion' => 'Islas Cook',
                'nacionalidad' => 'Neozelandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FRO',
                'iso' => 'FO',
                'descripcion' => 'Islas Feroe',
                'nacionalidad' => 'Feroense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'HMD',
                'iso' => 'HM',
                'descripcion' => 'Islas Heard y McDonald',
                'nacionalidad' => 'Heardésana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FLK',
                'iso' => 'FK',
                'descripcion' => 'Islas Malvinas',
                'nacionalidad' => 'Malvidensa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MHL',
                'iso' => 'MH',
                'descripcion' => 'Islas Marshall',
                'nacionalidad' => 'Marshalésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NFK',
                'iso' => 'NF',
                'descripcion' => 'Islas NorkFolk',
                'nacionalidad' => 'Neozelandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PAW',
                'iso' => 'PW',
                'descripcion' => 'Islas Palao',
                'nacionalidad' => 'Paluana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PCN',
                'iso' => 'PN',
                'descripcion' => 'Islas Pitcairn',
                'nacionalidad' => 'Norfolkense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SLB',
                'iso' => 'SB',
                'descripcion' => 'Islas Salomón',
                'nacionalidad' => 'Salomonensa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SJM',
                'iso' => 'SJ',
                'descripcion' => 'Islas Svalbard y Jan Mayen',
                'nacionalidad' => 'Noruega',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TCA',
                'iso' => 'TC',
                'descripcion' => 'Islas Turcas y Caicos',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VGB',
                'iso' => 'VG',
                'descripcion' => 'Islas Virgenes Británicas',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VIR',
                'iso' => 'VI',
                'descripcion' => 'Islas Virgenes de los Estados Unidos de América',
                'nacionalidad' => 'Estadounidense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ISR',
                'iso' => 'IL',
                'descripcion' => 'Israel',
                'nacionalidad' => 'Israelí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ITA',
                'iso' => 'IT',
                'descripcion' => 'Italia',
                'nacionalidad' => 'Italiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'JAM',
                'iso' => 'JM',
                'descripcion' => 'Jamaica',
                'nacionalidad' => 'Jamaiquina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'JPN',
                'iso' => 'JP',
                'descripcion' => 'Japón',
                'nacionalidad' => 'Japonésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'JER',
                'iso' => 'JE',
                'descripcion' => 'Jersey',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'JOR',
                'iso' => 'JO',
                'descripcion' => 'Jordania',
                'nacionalidad' => 'Jordana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KAZ',
                'iso' => 'KZ',
                'descripcion' => 'Kazajstán',
                'nacionalidad' => 'Kazaja',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KEN',
                'iso' => 'KE',
                'descripcion' => 'Kenia',
                'nacionalidad' => 'Kenia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KGZ',
                'iso' => 'KG',
                'descripcion' => 'Kirguistán',
                'nacionalidad' => 'Kirguís',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KIR',
                'iso' => 'KI',
                'descripcion' => 'Kiribati',
                'nacionalidad' => 'Kiribatiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KWT',
                'iso' => 'KW',
                'descripcion' => 'Kuwait',
                'nacionalidad' => 'Kuwaití',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LAO',
                'iso' => 'LA',
                'descripcion' => 'Laos',
                'nacionalidad' => 'Laosiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LSO',
                'iso' => 'LS',
                'descripcion' => 'Lesotho',
                'nacionalidad' => 'Lesotensa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LVA',
                'iso' => 'LV',
                'descripcion' => 'Letonia',
                'nacionalidad' => 'Letoniana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LBN',
                'iso' => 'LB',
                'descripcion' => 'Líbano',
                'nacionalidad' => 'Libanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LBR',
                'iso' => 'LR',
                'descripcion' => 'Liberia',
                'nacionalidad' => 'Liberiana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LBY',
                'iso' => 'LY',
                'descripcion' => 'Libia',
                'nacionalidad' => 'Libia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LIE',
                'iso' => 'LI',
                'descripcion' => 'Liechtenstein',
                'nacionalidad' => 'Liechtensteiniana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LTU',
                'iso' => 'LT',
                'descripcion' => 'Lituania',
                'nacionalidad' => 'Lituaniana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LUX',
                'iso' => 'LU',
                'descripcion' => 'Luxemburgo',
                'nacionalidad' => 'Luxemburgésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MAC',
                'iso' => 'MO',
                'descripcion' => 'Macao',
                'nacionalidad' => 'China',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MKD',
                'iso' => 'MK',
                'descripcion' => 'Macedonia',
                'nacionalidad' => 'Macedonia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MDG',
                'iso' => 'MG',
                'descripcion' => 'Madagascar',
                'nacionalidad' => 'Malgache',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MYS',
                'iso' => 'MY',
                'descripcion' => 'Malasia',
                'nacionalidad' => 'Malaya',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MWI',
                'iso' => 'MW',
                'descripcion' => 'Malaui',
                'nacionalidad' => 'Malauí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MDV',
                'iso' => 'MV',
                'descripcion' => 'Maldivas',
                'nacionalidad' => 'Maldiva',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MLI',
                'iso' => 'ML',
                'descripcion' => 'Mali',
                'nacionalidad' => 'Maliense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MLT',
                'iso' => 'MT',
                'descripcion' => 'Malta',
                'nacionalidad' => 'Maltés',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MAR',
                'iso' => 'MA',
                'descripcion' => 'Marruecos',
                'nacionalidad' => 'Marroquí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MTQ',
                'iso' => 'MQ',
                'descripcion' => 'Martinica',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MUS',
                'iso' => 'MU',
                'descripcion' => 'Mauricio',
                'nacionalidad' => 'Mauriciana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MRT',
                'iso' => 'MR',
                'descripcion' => 'Mauritania',
                'nacionalidad' => 'Mauritana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MYT',
                'iso' => 'YT',
                'descripcion' => 'Mayotte',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MEX',
                'iso' => 'MX',
                'descripcion' => 'México',
                'nacionalidad' => 'Mexicana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'FSM',
                'iso' => 'FM',
                'descripcion' => 'Micronesia',
                'nacionalidad' => 'Micronesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MDA',
                'iso' => 'MD',
                'descripcion' => 'Moldovia',
                'nacionalidad' => 'Moldava',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MCO',
                'iso' => 'MC',
                'descripcion' => 'Mónaco',
                'nacionalidad' => 'Monaquésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MNG',
                'iso' => 'MN',
                'descripcion' => 'Mongolia',
                'nacionalidad' => 'Mongóla',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MNE',
                'iso' => 'ME',
                'descripcion' => 'Montenegro',
                'nacionalidad' => 'Montenegrina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MSR',
                'iso' => 'MS',
                'descripcion' => 'Montserrat',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MOZ',
                'iso' => 'MZ',
                'descripcion' => 'Mozambique',
                'nacionalidad' => 'Mozambiqueña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'MMR',
                'iso' => 'MM',
                'descripcion' => 'Myanmar',
                'nacionalidad' => 'Birmana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NAM',
                'iso' => 'NA',
                'descripcion' => 'Namibia',
                'nacionalidad' => 'Namibia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NRU',
                'iso' => 'NR',
                'descripcion' => 'Nauru',
                'nacionalidad' => 'Nauruana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NPL',
                'iso' => 'NP',
                'descripcion' => 'Nepal',
                'nacionalidad' => 'Nepalí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NIC',
                'iso' => 'NI',
                'descripcion' => 'Nicaragua',
                'nacionalidad' => 'Nicaraguense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NER',
                'iso' => 'NE',
                'descripcion' => 'Níger',
                'nacionalidad' => 'Nigeriana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NGA',
                'iso' => 'NG',
                'descripcion' => 'Nigeria',
                'nacionalidad' => 'Nigeriana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NIU',
                'iso' => 'NE',
                'descripcion' => 'Niue',
                'nacionalidad' => 'Niuana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NOR',
                'iso' => 'NO',
                'descripcion' => 'Noruega',
                'nacionalidad' => 'Noruega',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NCL',
                'iso' => 'NC',
                'descripcion' => 'Nueva Caledonia',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NZL',
                'iso' => 'NZ',
                'descripcion' => 'Nueva Zelanda',
                'nacionalidad' => 'Neozelandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'OMN',
                'iso' => 'OM',
                'descripcion' => 'Omán',
                'nacionalidad' => 'Omana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'NLD',
                'iso' => 'NL',
                'descripcion' => 'Paises Bajos',
                'nacionalidad' => 'Holendésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PAK',
                'iso' => 'PK',
                'descripcion' => 'Pakistán',
                'nacionalidad' => 'Pakistaní',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PSE',
                'iso' => 'PS',
                'descripcion' => 'Palestina',
                'nacionalidad' => 'Palestina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PAN',
                'iso' => 'PA',
                'descripcion' => 'Panamá',
                'nacionalidad' => 'Panaméña',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PNG',
                'iso' => 'PG',
                'descripcion' => 'Papúa Nueva Guinea',
                'nacionalidad' => 'Papú',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PRY',
                'iso' => 'PY',
                'descripcion' => 'Paraguay',
                'nacionalidad' => 'Paraguaya',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PER',
                'iso' => 'PE',
                'descripcion' => 'Perú',
                'nacionalidad' => 'Peruana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PYF',
                'iso' => 'PF',
                'descripcion' => 'Polinesia Francesa',
                'nacionalidad' => 'Francesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'POL',
                'iso' => 'PL',
                'descripcion' => 'Polonia',
                'nacionalidad' => 'Polaca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PRT',
                'iso' => 'PT',
                'descripcion' => 'Portugal',
                'nacionalidad' => 'Portuguésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'PRI',
                'iso' => 'PR',
                'descripcion' => 'Puerto Rico',
                'nacionalidad' => 'Estadounidense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'QAT',
                'iso' => 'QA',
                'descripcion' => 'Qatar',
                'nacionalidad' => 'Katarí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'GBR',
                'iso' => 'GB',
                'descripcion' => 'Reino Unido',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CAF',
                'iso' => 'CF',
                'descripcion' => 'República Centro-Africana',
                'nacionalidad' => 'Centroafricana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CZE',
                'iso' => 'CZ',
                'descripcion' => 'República Checa',
                'nacionalidad' => 'Checa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DOM',
                'iso' => 'DO',
                'descripcion' => 'República Dominicana',
                'nacionalidad' => 'Dominicana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'REU',
                'iso' => 'RE',
                'descripcion' => 'Reunión',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'RWA',
                'iso' => 'RW',
                'descripcion' => 'Ruanda',
                'nacionalidad' => 'Ruandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ROU',
                'iso' => 'RO',
                'descripcion' => 'Rumanía',
                'nacionalidad' => 'Rumana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'RUS',
                'iso' => 'RU',
                'descripcion' => 'Rusia',
                'nacionalidad' => 'Rusa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ESH',
                'iso' => 'EH',
                'descripcion' => 'Sahara Occidental',
                'nacionalidad' => 'Saharauis',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'WSM',
                'iso' => 'WS',
                'descripcion' => 'Samoa',
                'nacionalidad' => 'Samoana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ASM',
                'iso' => 'AS',
                'descripcion' => 'Samoa Americana',
                'nacionalidad' => 'Samoana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'BLE',
                'iso' => 'BL',
                'descripcion' => 'San Bartolomé',
                'nacionalidad' => 'Francesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'KNA',
                'iso' => 'KN',
                'descripcion' => 'San Cristóbal y Nieves',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SMR',
                'iso' => 'SM',
                'descripcion' => 'San Marino',
                'nacionalidad' => 'Dálmata',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SPM',
                'iso' => 'PM',
                'descripcion' => 'San Pedro y Miquelón',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VCT',
                'iso' => 'VC',
                'descripcion' => 'San Vicente y las Granadinas',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SHN',
                'iso' => 'SH',
                'descripcion' => 'Santa Helena',
                'nacionalidad' => 'Ecuatoriana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LCA',
                'iso' => 'LC',
                'descripcion' => 'Santa Lucía',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'STP',
                'iso' => 'ST',
                'descripcion' => 'Santo Tomé y Príncipe',
                'nacionalidad' => 'Portuguésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SEN',
                'iso' => 'SN',
                'descripcion' => 'Senegal',
                'nacionalidad' => 'Senegalésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SRB',
                'iso' => 'RS',
                'descripcion' => 'Serbia y Montenegro',
                'nacionalidad' => 'Serbia',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SYC',
                'iso' => 'SC',
                'descripcion' => 'Seychelles',
                'nacionalidad' => 'Seychelense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SLE',
                'iso' => 'SL',
                'descripcion' => 'Sierra Leona',
                'nacionalidad' => 'Sierraleonesa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SGP',
                'iso' => 'SG',
                'descripcion' => 'Singapur',
                'nacionalidad' => 'Singapurense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SYR',
                'iso' => 'SY',
                'descripcion' => 'Siria',
                'nacionalidad' => 'Siria',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SOM',
                'iso' => 'SO',
                'descripcion' => 'Somalia',
                'nacionalidad' => 'Somalí',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'LKA',
                'iso' => 'LK',
                'descripcion' => 'Sri Lanka',
                'nacionalidad' => 'Ceilandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SWZ',
                'iso' => 'SZ',
                'descripcion' => 'Suazilandia',
                'nacionalidad' => 'Suazi',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ZAF',
                'iso' => 'ZA',
                'descripcion' => 'Sudáfrica',
                'nacionalidad' => 'Sudafricana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SDN',
                'iso' => 'SD',
                'descripcion' => 'Sudán',
                'nacionalidad' => 'Sudanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SWE',
                'iso' => 'SE',
                'descripcion' => 'Suecia',
                'nacionalidad' => 'Sueca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'CHE',
                'iso' => 'CH',
                'descripcion' => 'Suiza',
                'nacionalidad' => 'Suiza',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'SUR',
                'iso' => 'SR',
                'descripcion' => 'Surinam',
                'nacionalidad' => 'Surinamésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'THA',
                'iso' => 'TH',
                'descripcion' => 'Tailandia',
                'nacionalidad' => 'Tailandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TWN',
                'iso' => 'TW',
                'descripcion' => 'Taiwán',
                'nacionalidad' => 'Taiwanésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TZA',
                'iso' => 'TH',
                'descripcion' => 'Tanzania',
                'nacionalidad' => 'Tanzana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TJK',
                'iso' => 'TJ',
                'descripcion' => 'Tayikistán',
                'nacionalidad' => 'Tayika',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'IOT',
                'iso' => 'IO',
                'descripcion' => 'Territorio Británico del Océano Índico',
                'nacionalidad' => 'Británica',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ATF',
                'iso' => 'TF',
                'descripcion' => 'Territorios Australes Franceses',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TLS',
                'iso' => 'TL',
                'descripcion' => 'Timor Oriental',
                'nacionalidad' => 'Portuguésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TGO',
                'iso' => 'TG',
                'descripcion' => 'Togo',
                'nacionalidad' => 'Togolésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TKL',
                'iso' => 'TK',
                'descripcion' => 'Tokelau',
                'nacionalidad' => 'Neozelandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TON',
                'iso' => 'TO',
                'descripcion' => 'Tonga',
                'nacionalidad' => 'Tongana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TTO',
                'iso' => 'TT',
                'descripcion' => 'Trinidad y Tobago',
                'nacionalidad' => 'Trinitense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TUN',
                'iso' => 'TN',
                'descripcion' => 'Túnez',
                'nacionalidad' => 'Tunecina',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TKM',
                'iso' => 'TM',
                'descripcion' => 'Turkmenistán',
                'nacionalidad' => 'Turca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TUR',
                'iso' => 'TR',
                'descripcion' => 'Turquía',
                'nacionalidad' => 'Turca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'TUV',
                'iso' => 'TV',
                'descripcion' => 'Tuvalu',
                'nacionalidad' => 'Tuvaluana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'UKR',
                'iso' => 'UA',
                'descripcion' => 'Ucrania',
                'nacionalidad' => 'Ucraniana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'UGA',
                'iso' => 'UG',
                'descripcion' => 'Uganda',
                'nacionalidad' => 'Ugandésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'URY',
                'iso' => 'UY',
                'descripcion' => 'Uruguay',
                'nacionalidad' => 'Uruguaya',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'UZB',
                'iso' => 'UZ',
                'descripcion' => 'Uzbekistán',
                'nacionalidad' => 'Uzbeca',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VUT',
                'iso' => 'VU',
                'descripcion' => 'Vanuatu',
                'nacionalidad' => 'Vanuatuense',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VEN',
                'iso' => 'VE',
                'descripcion' => 'Venezuela',
                'nacionalidad' => 'Venezolana',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'VNM',
                'iso' => 'VN',
                'descripcion' => 'Vietnam',
                'nacionalidad' => 'Vietnamita',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'WLF',
                'iso' => 'WF',
                'descripcion' => 'Wallis y Futuna',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'YEM',
                'iso' => 'YE',
                'descripcion' => 'Yemen',
                'nacionalidad' => 'Jemení',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'DJI',
                'iso' => 'DJ',
                'descripcion' => 'Yibuti',
                'nacionalidad' => 'Francésa',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ZMB',
                'iso' => 'ZM',
                'descripcion' => 'Zambia',
                'nacionalidad' => 'Zambes',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
            [
                'codigo' => 'ZWE',
                'iso' => 'ZW',
                'descripcion' => 'Zimbabue',
                'nacionalidad' => 'Zimbabues',
                'activo' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()->addWeeks(2),
            ],
        ];

        DB::table('paises')->insert($paises);
    }
}
